version: '2'
services:
  ghost:
    image: "quay.io/danfercf/ghost-pvpgn-x64:0.3.0"
    volumes:
      - /usr/local/ghost/maps:/usr/local/ghost/maps
      - /usr/local/ghost/replays:/usr/local/ghost/replays
      - /usr/local/ghost/mapcfgs:/usr/local/ghost/mapcfgs
    environment:
      #GENERAL
      BOT_HOST_PORT: 6116
      BOT_MAX_GAMES: 5
      BOT_COMMAND_TRIGGER: .
      BOT_SAVE_REPLAYS: 1
      BOT_NAME: "|cFFFF80FFLMK"
      BOT_SPOOF_CHECK: 1
      BOT_AUTOKICK_PING: 400
      BOT_DEFAULT_MAP: dota
      ADMIN_PORT: 6113
      ADMIN_PASSWORD:
      #GPROXY
      BOT_GPROXY_RECONNECT: 6117
      BOT_GPROXY_PORT: 6114
      BOT_RECONNECT_TIMEOUT: 3
      #AUTOHOST
      AUTOHOST_MAX_GAMES: 5
      AUTO_HOST_PLAYERS: 10
      AUTOHOST_GAME_NAME: Nioje Asno
      AUTOHOST_OWNER: oMy
      #MYSQL
      MYSQL_SERVER: 127.0.0.1
      MYSQL_DB_NAME: ghost
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_PORT: 3306
      #BNET
      BNET_SERVER_HOST: 167.71.188.159
      BNET_SERVER_ALIAS: LMK SERVER
      BNET_BOT_USERNAME: omy-bot
      BNET_BOT_PASSWORD: 12345
      BNET_BOT_CHANNEL: Bots
      BNET_BOT_ADMIN: oMy
      BNET_BOT_TRIGGER: .
    network_mode: host
    container_name: ghost1
    command: ["./ghost.sh"]
    restart: always
    #links:
      #- mysql:db
networks:
  default:
    external:
      name: pvpgn_default